# Generated by Django 5.1.1 on 2024-11-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
    ]
